$axure.loadCurrentPage({
  "url":"scandevice.html",
  "generationDate":new Date(1503911358435.35),
  "isCanvasEnabled":false,
  "variables":["NavigationSpread"],
  "page":{
    "packageId":"f1e452316db24ee08a55a10b235e0e3a",
    "type":"Axure:Page",
    "name":"ScanDevice",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7c54a64aaebf42b8b44f57b74303b7b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFCC66},
{
                  "color":0xFFFFCC66},
{
                  "color":0xFFECEF76},
{
                  "color":0xFFECEF76}]},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9713cfea13bc4b3daabb6fdac29e0618",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFCC66},
{
                      "color":0xFFFFCC66},
{
                      "color":0xFFECEF76},
{
                      "color":0xFFECEF76}]},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u441.png"}},
{
          "id":"52f0555e3afb426e8e116b2405de8539",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":480,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8c46ca934384cac81954d31bf596903",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":480,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u443.png"}},
{
          "id":"0a4016de93bd49cb89674d6b81eb5fd6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":145},
            "size":{
              "width":298,
              "height":315}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e962830ae1b4e53bf61031d8d54f93f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":145},
                "size":{
                  "width":298,
                  "height":315}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 DeviceDetails",
                      "target":{
                        "targetType":"page",
                        "url":"devicedetails.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/orders_1/u589.png"}},
{
          "id":"3649fc6deada4267af97d9f08e9e022d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":62.5,
              "y":520},
            "size":{
              "width":337,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eb6ebf16d11493194f865fb1df6e576",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":62.5,
                  "y":520},
                "size":{
                  "width":337,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d74f98515b44499a57e47bdec219a3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0x4C000000}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000}}},
            "fill":{
              "fillType":"solid",
              "color":0x33000000},
            "location":{
              "x":169,
              "y":600},
            "size":{
              "width":142,
              "height":48},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bf24aaa223941648add3afcc0b79ab8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x4C000000}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7F000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0x33000000},
                "location":{
                  "x":169,
                  "y":600},
                "size":{
                  "width":142,
                  "height":48},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders_1/u353.png",
            "mouseOver~":"images/orders_1/u353_mouseOver.png",
            "mouseDown~":"images/orders_1/u353_mouseDown.png"}},
{
          "id":"04bc34b9fef94388b34e6f387132295b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0x4C000000}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000}}},
            "fill":{
              "fillType":"solid",
              "color":0x33000000},
            "location":{
              "x":18,
              "y":43},
            "size":{
              "width":92,
              "height":48},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a038c91d7f8b4d30a9d740c1321f01f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x4C000000}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7F000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0x33000000},
                "location":{
                  "x":18,
                  "y":43},
                "size":{
                  "width":92,
                  "height":48},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Main",
                      "target":{
                        "targetType":"page",
                        "url":"main.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u900.png",
            "mouseOver~":"images/main/u900_mouseOver.png",
            "mouseDown~":"images/main/u900_mouseDown.png"}},
{
          "id":"acbf6c03f295432e91e6199717b5e0fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":51},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09c18bb6ff794b63ae37d6dd0f1f1355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":51},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home3/u1031.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7c54a64aaebf42b8b44f57b74303b7b4":{
      "scriptId":"u0"},
    "9713cfea13bc4b3daabb6fdac29e0618":{
      "scriptId":"u1"},
    "52f0555e3afb426e8e116b2405de8539":{
      "scriptId":"u2"},
    "e8c46ca934384cac81954d31bf596903":{
      "scriptId":"u3"},
    "0a4016de93bd49cb89674d6b81eb5fd6":{
      "scriptId":"u4"},
    "4e962830ae1b4e53bf61031d8d54f93f":{
      "scriptId":"u5"},
    "3649fc6deada4267af97d9f08e9e022d":{
      "scriptId":"u6"},
    "2eb6ebf16d11493194f865fb1df6e576":{
      "scriptId":"u7"},
    "5d74f98515b44499a57e47bdec219a3a":{
      "scriptId":"u8"},
    "9bf24aaa223941648add3afcc0b79ab8":{
      "scriptId":"u9"},
    "04bc34b9fef94388b34e6f387132295b":{
      "scriptId":"u10"},
    "a038c91d7f8b4d30a9d740c1321f01f8":{
      "scriptId":"u11"},
    "acbf6c03f295432e91e6199717b5e0fc":{
      "scriptId":"u12"},
    "09c18bb6ff794b63ae37d6dd0f1f1355":{
      "scriptId":"u13"}}});