$axure.loadCurrentPage({
  "url":"more.html",
  "generationDate":new Date(1503911358394.35),
  "isCanvasEnabled":false,
  "variables":["NavigationSpread"],
  "page":{
    "packageId":"49f2b1bec956434ebc4d3fc87ec2753c",
    "type":"Axure:Page",
    "name":"More",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e64b49509ccd4558ba908c021a1e4194",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFCC66},
{
                  "color":0xFFFFCC66},
{
                  "color":0xFFECEF76},
{
                  "color":0xFFECEF76}]},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0a5dc23e8a045bd8676276806bf64e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFCC66},
{
                      "color":0xFFFFCC66},
{
                      "color":0xFFECEF76},
{
                      "color":0xFFECEF76}]},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u441.png"}},
{
          "id":"24b02162a640488f8d38b469cdece644",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":480,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d669878175084d83ba271de3a20b0f9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":480,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u443.png"}},
{
          "id":"0c47b40465544805b89f82b6fb460363",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":119},
            "size":{
              "width":478,
              "height":71},
            "borderWidth":"-1",
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff1be9b8aa746e081aa4f65d366093f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":119},
                "size":{
                  "width":478,
                  "height":71},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u972.png"}},
{
          "id":"e1483a3acde74e16a3e891653c402d96",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":210,
              "y":55},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75c47ba420904a51bed7ebab3bfb1f56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":210,
                  "y":55},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de0e20914ad2408e9f687fe3af1cad5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0x4C000000}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000}}},
            "fill":{
              "fillType":"solid",
              "color":0x33000000},
            "location":{
              "x":18,
              "y":43},
            "size":{
              "width":92,
              "height":48},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4769fc49239a4995bb4f1d824c16130a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x4C000000}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7F000000}}},
                "fill":{
                  "fillType":"solid",
                  "color":0x33000000},
                "location":{
                  "x":18,
                  "y":43},
                "size":{
                  "width":92,
                  "height":48},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Main",
                      "target":{
                        "targetType":"page",
                        "url":"main.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/main/u900.png",
            "mouseOver~":"images/main/u900_mouseOver.png",
            "mouseDown~":"images/main/u900_mouseDown.png"}},
{
          "id":"d66c55dc71574bd095eecfefc7e4fd21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":51},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6acb1d6fefc9421aae3ed228ca8b6cf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":51},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home3/u1031.png"}},
{
          "id":"9cd6cd9fa0114a7398b9c2532c2bff0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":210},
            "size":{
              "width":478,
              "height":160},
            "borderWidth":"-1",
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df74aa8f0257493bae8c8a8cf565e3ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":210},
                "size":{
                  "width":478,
                  "height":160},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u976.png"}},
{
          "id":"24b3e5cf6e40469d8060c8dce29358df",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":18,
              "y":140},
            "size":{
              "width":73,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff2656e8bc0a4c50beed44be66d9fb4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":18,
                  "y":140},
                "size":{
                  "width":73,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ff7d333a8bf4aa4a08f2839c0b892e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":130},
            "size":{
              "width":200,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdefd602ef03426dae43004ae5af0754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":130},
                "size":{
                  "width":200,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c43e8c0bb4024cadb97920b588b48829",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF669966,
              "opacity":1},
            "location":{
              "x":320,
              "y":144},
            "size":{
              "width":79,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c4e2dab7a7944e889b06a68d400751d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF669966,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":144},
                "size":{
                  "width":79,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9a2dbb369974ac8a26158b7f49824bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":139},
            "size":{
              "width":34,
              "height":34},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8af7f522002144ffaf0f36ca093fa4d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":139},
                "size":{
                  "width":34,
                  "height":34},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u60.png"}},
{
          "id":"d2e7ea5ed5c7444aaf5d65871f7724c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":18,
              "y":232},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97ceed6f23d144899fcba9a514e64458",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":18,
                  "y":232},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d81b63e087da48f1a5307f781006b9ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":228},
            "size":{
              "width":34,
              "height":34},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2b84ee7c39e4d87b68a05dd0647d916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":228},
                "size":{
                  "width":34,
                  "height":34},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u60.png"}},
{
          "id":"f5dc12c01aff4c979da6c1274dc3bf7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":18,
              "y":316},
            "size":{
              "width":321,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcaab06884524223856315545d11a850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":18,
                  "y":316},
                "size":{
                  "width":321,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa86c1bdc1e6452285a2fc9a38a3a074",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":322},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a11c165cbf8642ceb60a475b7adadc21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":322},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4ce1f47e613f4553a81a25f20d2143e4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":282},
            "size":{
              "width":479,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/main/u988_line.png"}},
{
          "id":"11f63e43ba5b4b709356bf9e640b8852",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":690},
            "size":{
              "width":478,
              "height":60},
            "borderWidth":"-1",
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0109623b90ce41bab356446ad7bf4c62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":690},
                "size":{
                  "width":478,
                  "height":60},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/main/u989.png"}},
{
          "id":"8d091cb2f2664677a84de71c27aeeb28",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF7171,
              "opacity":1},
            "location":{
              "x":194,
              "y":708},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4449b2e1e3c54b719688babb3854a13d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF7171,
                  "opacity":1},
                "location":{
                  "x":194,
                  "y":708},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e64b49509ccd4558ba908c021a1e4194":{
      "scriptId":"u0"},
    "e0a5dc23e8a045bd8676276806bf64e1":{
      "scriptId":"u1"},
    "24b02162a640488f8d38b469cdece644":{
      "scriptId":"u2"},
    "d669878175084d83ba271de3a20b0f9a":{
      "scriptId":"u3"},
    "0c47b40465544805b89f82b6fb460363":{
      "scriptId":"u4"},
    "aff1be9b8aa746e081aa4f65d366093f":{
      "scriptId":"u5"},
    "e1483a3acde74e16a3e891653c402d96":{
      "scriptId":"u6"},
    "75c47ba420904a51bed7ebab3bfb1f56":{
      "scriptId":"u7"},
    "de0e20914ad2408e9f687fe3af1cad5b":{
      "scriptId":"u8"},
    "4769fc49239a4995bb4f1d824c16130a":{
      "scriptId":"u9"},
    "d66c55dc71574bd095eecfefc7e4fd21":{
      "scriptId":"u10"},
    "6acb1d6fefc9421aae3ed228ca8b6cf3":{
      "scriptId":"u11"},
    "9cd6cd9fa0114a7398b9c2532c2bff0d":{
      "scriptId":"u12"},
    "df74aa8f0257493bae8c8a8cf565e3ad":{
      "scriptId":"u13"},
    "24b3e5cf6e40469d8060c8dce29358df":{
      "scriptId":"u14"},
    "ff2656e8bc0a4c50beed44be66d9fb4e":{
      "scriptId":"u15"},
    "8ff7d333a8bf4aa4a08f2839c0b892e4":{
      "scriptId":"u16"},
    "cdefd602ef03426dae43004ae5af0754":{
      "scriptId":"u17"},
    "c43e8c0bb4024cadb97920b588b48829":{
      "scriptId":"u18"},
    "5c4e2dab7a7944e889b06a68d400751d":{
      "scriptId":"u19"},
    "b9a2dbb369974ac8a26158b7f49824bc":{
      "scriptId":"u20"},
    "8af7f522002144ffaf0f36ca093fa4d8":{
      "scriptId":"u21"},
    "d2e7ea5ed5c7444aaf5d65871f7724c6":{
      "scriptId":"u22"},
    "97ceed6f23d144899fcba9a514e64458":{
      "scriptId":"u23"},
    "d81b63e087da48f1a5307f781006b9ad":{
      "scriptId":"u24"},
    "a2b84ee7c39e4d87b68a05dd0647d916":{
      "scriptId":"u25"},
    "f5dc12c01aff4c979da6c1274dc3bf7c":{
      "scriptId":"u26"},
    "dcaab06884524223856315545d11a850":{
      "scriptId":"u27"},
    "fa86c1bdc1e6452285a2fc9a38a3a074":{
      "scriptId":"u28"},
    "a11c165cbf8642ceb60a475b7adadc21":{
      "scriptId":"u29"},
    "4ce1f47e613f4553a81a25f20d2143e4":{
      "scriptId":"u30"},
    "11f63e43ba5b4b709356bf9e640b8852":{
      "scriptId":"u31"},
    "0109623b90ce41bab356446ad7bf4c62":{
      "scriptId":"u32"},
    "8d091cb2f2664677a84de71c27aeeb28":{
      "scriptId":"u33"},
    "4449b2e1e3c54b719688babb3854a13d":{
      "scriptId":"u34"}}});