$axure.loadCurrentPage({
  "url":"reportcontent.html",
  "generationDate":new Date(1503911352147.99),
  "isCanvasEnabled":false,
  "variables":["NavigationSpread"],
  "page":{
    "packageId":"c210fc980d7f4a90b694b33aaab55d3b",
    "type":"Axure:Page",
    "name":"ReportContent",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"60cb741489844fe2aaf5b306f2a6d1d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":615,
              "height":1000},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b359c8e04b4427bb568e232e0a6a071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":615,
                  "height":1000},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u0.png"}},
{
          "id":"56e35b4e88d74723bb8f75804d8c28c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":57,
              "y":280},
            "size":{
              "width":159,
              "height":88},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88ab1ea1906e4e9daddbabc5af959690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":57,
                  "y":280},
                "size":{
                  "width":159,
                  "height":88},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u2.png"}},
{
          "id":"2a4399da2d514835ab01aaed7ac9f4fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":77,
              "y":330},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43ca1e4df3dd474db4b869f0116ba13b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":77,
                  "y":330},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69887e50d9be4b9690982ae5d832d8af",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":112,
              "y":393},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ad20ae3c7aa4e3abcc6bf132181aee4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":112,
                  "y":393},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70f4011cd37749a38705b15878bf626a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":388,
              "y":393},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5004b40d8ff84906b0ece4ef4396921d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":388,
                  "y":393},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6114dd00d324778be47943873a5b4e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFCC00,
              "opacity":1},
            "location":{
              "x":135,
              "y":306},
            "size":{
              "width":41,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e57a3f016c04d70b2a7d0a9fa6978df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00,
                  "opacity":1},
                "location":{
                  "x":135,
                  "y":306},
                "size":{
                  "width":41,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fade01a277d74025adf79befd7bf933a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF669900,
              "opacity":1},
            "location":{
              "x":193,
              "y":393},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd15c859dc684aacb75f70bb6573c155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF669900,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":393},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d8667c2a7a6465a8b91c3f53fb1aa3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF669900,
              "opacity":1},
            "location":{
              "x":514,
              "y":393},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72d3a0e5f797449f95d8e0affc0562f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF669900,
                  "opacity":1},
                "location":{
                  "x":514,
                  "y":393},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"117f0554b29d4ff6af98dd16413e034e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":177,
              "y":323},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1db13378206c4a5bb1c226438fab5442",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":177,
                  "y":323},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"516dd419e02c4d89b39388d52080bb5c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":260},
            "size":{
              "width":615,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF546172}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/reportcontent/u18_line.png"}},
{
          "id":"69fe27342f53495caddc9fa342885922",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":300},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e80a153005824794a5799e8d05e36f39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":300},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home2/u820.png"}},
{
          "id":"71c7ba3c43294842ac2d7a3bddd4adc9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":293},
            "size":{
              "width":10,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF546172}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/reportcontent/u21_line.png"}},
{
          "id":"6685296b3f144e0997838af6b54035d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":224,
              "y":280},
            "size":{
              "width":159,
              "height":88},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5af7642e11e84407a5a317f962a3fcc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":224,
                  "y":280},
                "size":{
                  "width":159,
                  "height":88},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u2.png"}},
{
          "id":"17625ada6e7b49d6af076a01bda75c75",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":293},
            "size":{
              "width":10,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF546172}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/reportcontent/u21_line.png"}},
{
          "id":"a1c4c40025964d648c4a428ec1fd9d90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":392,
              "y":280},
            "size":{
              "width":159,
              "height":88},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"181c04257aa844c6aad018e3b08aa908",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":392,
                  "y":280},
                "size":{
                  "width":159,
                  "height":88},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u2.png"}},
{
          "id":"f2b5c28135474399b73976f491a43a2a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":293},
            "size":{
              "width":10,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF546172}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/reportcontent/u21_line.png"}},
{
          "id":"06c75bc708e848429ac591d95a1d54df",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":248,
              "y":330},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46cd23dcb9f041b9bee7fa38137a64ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":248,
                  "y":330},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"172ef8bad2ae405e9dd1d2e0ebdab4d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":412,
              "y":330},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d2b05f31dce4712acb6d5368d5a155b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":412,
                  "y":330},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a96f7c399c514a4aa071e4faeba54715",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":320,
              "y":307},
            "size":{
              "width":21,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5acf98ec4dc441cc90a170fbfe1f993d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":307},
                "size":{
                  "width":21,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"245a3a26f0e24f9780aab2f4ddd44016",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CCFF,
              "opacity":1},
            "location":{
              "x":485,
              "y":307},
            "size":{
              "width":21,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b967189c855f4f6db51a07301d95f4f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CCFF,
                  "opacity":1},
                "location":{
                  "x":485,
                  "y":307},
                "size":{
                  "width":21,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddc53c4ff6224b5a93c9ba76ab3c161d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":345,
              "y":324},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3044e2adbe304d0eb4f9d7612474b8b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":345,
                  "y":324},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb6af2d58c5c485c86c31264d6d914cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":508,
              "y":324},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9e4ee9cc44b4474973c8c59a6257206",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":508,
                  "y":324},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b17e1274a0c4400aa565701150c2135",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":296},
            "size":{
              "width":23,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7678c13e9d420a92ae6258ad5f2c0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":296},
                "size":{
                  "width":23,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u40.png"}},
{
          "id":"ff9ca1d4d313430b80c7cd83d07e5894",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":414,
              "y":299},
            "size":{
              "width":26,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3880289281c4cbc87504c46cccb9dcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":414,
                  "y":299},
                "size":{
                  "width":26,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u42.png"}},
{
          "id":"13132dce66a942cda265ea1c1cc9c804",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":11,
              "y":521},
            "size":{
              "width":582,
              "height":72},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce8405be0f8545a1a37369871edfe986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":11,
                  "y":521},
                "size":{
                  "width":582,
                  "height":72},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u44.png"}},
{
          "id":"ff126ffba1d044d4a55b023cbcaf1e6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":51,
              "y":548},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4322099264ea476baf382ba31b1f1d8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":548},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"430074024d104c7b867a735a4374fbb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CCFF,
              "opacity":1},
            "location":{
              "x":165,
              "y":541},
            "size":{
              "width":81,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c10601826b1f45c28f569f7f807f44dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CCFF,
                  "opacity":1},
                "location":{
                  "x":165,
                  "y":541},
                "size":{
                  "width":81,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8ca9615d6624b47bf7f7114e251b164",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":246,
              "y":555},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b60ebb7b824d5bb22664d876526b80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":246,
                  "y":555},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdacfe63580f46a880491ede8e3c9be7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":363,
              "y":548},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2392bd5e0022497286cf9c02b3ca9615",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":363,
                  "y":548},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9da4dbfbe39641079b67a2268e60aa57",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":447,
              "y":541},
            "size":{
              "width":73,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af129290d218491ab88cc7a9046771e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":447,
                  "y":541},
                "size":{
                  "width":73,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78a09463ecdc489cabab1a8a12f9ca6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":520,
              "y":553},
            "size":{
              "width":13,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b49713889c5d4093a8ed73b8cb91bb35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":520,
                  "y":553},
                "size":{
                  "width":13,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf9cba57f30046628378a1aeedc6c0fc",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":529},
            "size":{
              "width":10,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF546172}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/reportcontent/u21_line.png"}},
{
          "id":"12ee1af996584f23a502575188f15d6c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":622},
            "size":{
              "width":103,
              "height":103},
            "rotation":"280",
            "textRotation":"280"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"615861bced8b450dafdd2ba4520c0449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":622},
                "size":{
                  "width":103,
                  "height":103},
                "rotation":"280",
                "textRotation":"280"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u59.png"}},
{
          "id":"6fe4736a3da74adc94d06dedcbb11c93",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":144,
              "y":628},
            "size":{
              "width":85,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"420e6fb13ed448f1b0cfc55a745b0c26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":144,
                  "y":628},
                "size":{
                  "width":85,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u61.png"}},
{
          "id":"02267a22bf354b948e8299e479c886e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6481B3},
            "location":{
              "x":273,
              "y":639},
            "size":{
              "width":11,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffe3c835abe24f6ebe2106eb7bf078b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6481B3},
                "location":{
                  "x":273,
                  "y":639},
                "size":{
                  "width":11,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u63.png"}},
{
          "id":"6d75c89ff8ae4964a9f3affc1bca5d0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDB4A37},
            "location":{
              "x":273,
              "y":659},
            "size":{
              "width":11,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"457c0e52f4424bd59dbf1cd715b02a15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDB4A37},
                "location":{
                  "x":273,
                  "y":659},
                "size":{
                  "width":11,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u65.png"}},
{
          "id":"857a9898c07641358ae21f6325e9534f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF474749},
            "location":{
              "x":273,
              "y":681},
            "size":{
              "width":11,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70da91ad98bb4bd78f8bf13c0b95afc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF474749},
                "location":{
                  "x":273,
                  "y":681},
                "size":{
                  "width":11,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u67.png"}},
{
          "id":"b80f3c68ee644b59a5348bb3a44e59a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF669900},
            "location":{
              "x":273,
              "y":703},
            "size":{
              "width":11,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0baa23e384d242dcaa886756b2d93c5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF669900},
                "location":{
                  "x":273,
                  "y":703},
                "size":{
                  "width":11,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u69.png"}},
{
          "id":"d8a479ee0ef941be9892380fa484aa04",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6481B3,
              "opacity":1},
            "location":{
              "x":302,
              "y":635},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8d5a35eb00d4d79aadcda2c62e4ccb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6481B3,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":635},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e320ae7671974371ae0bba29f1a45908",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFDB4A37,
              "opacity":1},
            "location":{
              "x":302,
              "y":657},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecd9d093277b477bbf1930dc51b4b2c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFDB4A37,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":657},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8deeaa07c8d64e84a9047792eea2b13f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":302,
              "y":679},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"726b821a16b44a00b38aa13767c1f2ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":679},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba6085a4e5c549d488fdd755bd71e7b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF669900,
              "opacity":1},
            "location":{
              "x":302,
              "y":701},
            "size":{
              "width":147,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2dc01a99525414fb7d95d02ab262806",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF669900,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":701},
                "size":{
                  "width":147,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"022b108906b04c8381c307450005a0d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":14,
              "y":750},
            "size":{
              "width":241,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e5699a88f8949aab8c1fcece535e4fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":750},
                "size":{
                  "width":241,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69889721c2a346d4ae12a8cc81accb68",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":790},
            "size":{
              "width":577,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9d7fc26db464de585fcc586accda72d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":790},
                "size":{
                  "width":577,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u81.png"}},
{
          "id":"4446c255058044deb9a5b2d2bd975e0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":11,
              "y":231},
            "size":{
              "width":181,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dd7a5e0dc4d4164b588a9c3ab824d2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":11,
                  "y":231},
                "size":{
                  "width":181,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u83.png"}},
{
          "id":"11ba7afe5c24402fb017f66f3a8739a5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":463},
            "size":{
              "width":615,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF546172}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/reportcontent/u18_line.png"}},
{
          "id":"135b41af9d4049f0a03b0a41784822f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF448FF4},
            "location":{
              "x":11,
              "y":434},
            "size":{
              "width":181,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b6e2c194d00412ea4fa8dc593f5b434",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF448FF4},
                "location":{
                  "x":11,
                  "y":434},
                "size":{
                  "width":181,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u86.png"}},
{
          "id":"587f488ffb634c45b3e61704fc1f417a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":615,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF546172}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/reportcontent/u18_line.png"}},
{
          "id":"d29370eea24c4f47b98e307b5e07726c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF669900},
            "location":{
              "x":11,
              "y":10},
            "size":{
              "width":181,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ed0e94ef2814019b2bec8968ed205f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF669900},
                "location":{
                  "x":11,
                  "y":10},
                "size":{
                  "width":181,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u89.png"}},
{
          "id":"d310e14a17484ac3b69014ef736261bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":200,
              "y":70},
            "size":{
              "width":36,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a166e2747a8e4ecaa889030e181f023f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":200,
                  "y":70},
                "size":{
                  "width":36,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u91.png"}},
{
          "id":"c56dcd08318e45f8bce5a19dc4693bc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":256,
              "y":70},
            "size":{
              "width":36,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2285a08d687549b6a90724987f41b63b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":256,
                  "y":70},
                "size":{
                  "width":36,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u91.png"}},
{
          "id":"533b7e62fc6e4160a85c6ad373fc3c29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":309,
              "y":70},
            "size":{
              "width":36,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db31738fd19841cdbe7a4bc94e9e7f97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":309,
                  "y":70},
                "size":{
                  "width":36,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u91.png"}},
{
          "id":"3715070b6789464d87fd09bfc7d755fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":371,
              "y":70},
            "size":{
              "width":36,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6c89ab485224f699b826d72dcf6f64d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":371,
                  "y":70},
                "size":{
                  "width":36,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/reportcontent/u97.png"}},
{
          "id":"b6436f7c35094fc7af52694286324314",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":14,
              "y":133},
            "size":{
              "width":565,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f82a705a62949aca919979b3775a150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":133},
                "size":{
                  "width":565,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ada0f4dedc4047e7befea44a9bed5b30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":76,
              "y":70},
            "size":{
              "width":51,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c90201eca11e4587be15e42ad23f2eae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":76,
                  "y":70},
                "size":{
                  "width":51,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "60cb741489844fe2aaf5b306f2a6d1d1":{
      "scriptId":"u0"},
    "7b359c8e04b4427bb568e232e0a6a071":{
      "scriptId":"u1"},
    "56e35b4e88d74723bb8f75804d8c28c1":{
      "scriptId":"u2"},
    "88ab1ea1906e4e9daddbabc5af959690":{
      "scriptId":"u3"},
    "2a4399da2d514835ab01aaed7ac9f4fc":{
      "scriptId":"u4"},
    "43ca1e4df3dd474db4b869f0116ba13b":{
      "scriptId":"u5"},
    "69887e50d9be4b9690982ae5d832d8af":{
      "scriptId":"u6"},
    "6ad20ae3c7aa4e3abcc6bf132181aee4":{
      "scriptId":"u7"},
    "70f4011cd37749a38705b15878bf626a":{
      "scriptId":"u8"},
    "5004b40d8ff84906b0ece4ef4396921d":{
      "scriptId":"u9"},
    "d6114dd00d324778be47943873a5b4e8":{
      "scriptId":"u10"},
    "0e57a3f016c04d70b2a7d0a9fa6978df":{
      "scriptId":"u11"},
    "fade01a277d74025adf79befd7bf933a":{
      "scriptId":"u12"},
    "bd15c859dc684aacb75f70bb6573c155":{
      "scriptId":"u13"},
    "2d8667c2a7a6465a8b91c3f53fb1aa3c":{
      "scriptId":"u14"},
    "72d3a0e5f797449f95d8e0affc0562f2":{
      "scriptId":"u15"},
    "117f0554b29d4ff6af98dd16413e034e":{
      "scriptId":"u16"},
    "1db13378206c4a5bb1c226438fab5442":{
      "scriptId":"u17"},
    "516dd419e02c4d89b39388d52080bb5c":{
      "scriptId":"u18"},
    "69fe27342f53495caddc9fa342885922":{
      "scriptId":"u19"},
    "e80a153005824794a5799e8d05e36f39":{
      "scriptId":"u20"},
    "71c7ba3c43294842ac2d7a3bddd4adc9":{
      "scriptId":"u21"},
    "6685296b3f144e0997838af6b54035d4":{
      "scriptId":"u22"},
    "5af7642e11e84407a5a317f962a3fcc1":{
      "scriptId":"u23"},
    "17625ada6e7b49d6af076a01bda75c75":{
      "scriptId":"u24"},
    "a1c4c40025964d648c4a428ec1fd9d90":{
      "scriptId":"u25"},
    "181c04257aa844c6aad018e3b08aa908":{
      "scriptId":"u26"},
    "f2b5c28135474399b73976f491a43a2a":{
      "scriptId":"u27"},
    "06c75bc708e848429ac591d95a1d54df":{
      "scriptId":"u28"},
    "46cd23dcb9f041b9bee7fa38137a64ad":{
      "scriptId":"u29"},
    "172ef8bad2ae405e9dd1d2e0ebdab4d1":{
      "scriptId":"u30"},
    "3d2b05f31dce4712acb6d5368d5a155b":{
      "scriptId":"u31"},
    "a96f7c399c514a4aa071e4faeba54715":{
      "scriptId":"u32"},
    "5acf98ec4dc441cc90a170fbfe1f993d":{
      "scriptId":"u33"},
    "245a3a26f0e24f9780aab2f4ddd44016":{
      "scriptId":"u34"},
    "b967189c855f4f6db51a07301d95f4f5":{
      "scriptId":"u35"},
    "ddc53c4ff6224b5a93c9ba76ab3c161d":{
      "scriptId":"u36"},
    "3044e2adbe304d0eb4f9d7612474b8b4":{
      "scriptId":"u37"},
    "cb6af2d58c5c485c86c31264d6d914cc":{
      "scriptId":"u38"},
    "c9e4ee9cc44b4474973c8c59a6257206":{
      "scriptId":"u39"},
    "4b17e1274a0c4400aa565701150c2135":{
      "scriptId":"u40"},
    "7b7678c13e9d420a92ae6258ad5f2c0c":{
      "scriptId":"u41"},
    "ff9ca1d4d313430b80c7cd83d07e5894":{
      "scriptId":"u42"},
    "a3880289281c4cbc87504c46cccb9dcc":{
      "scriptId":"u43"},
    "13132dce66a942cda265ea1c1cc9c804":{
      "scriptId":"u44"},
    "ce8405be0f8545a1a37369871edfe986":{
      "scriptId":"u45"},
    "ff126ffba1d044d4a55b023cbcaf1e6d":{
      "scriptId":"u46"},
    "4322099264ea476baf382ba31b1f1d8a":{
      "scriptId":"u47"},
    "430074024d104c7b867a735a4374fbb0":{
      "scriptId":"u48"},
    "c10601826b1f45c28f569f7f807f44dd":{
      "scriptId":"u49"},
    "a8ca9615d6624b47bf7f7114e251b164":{
      "scriptId":"u50"},
    "88b60ebb7b824d5bb22664d876526b80":{
      "scriptId":"u51"},
    "bdacfe63580f46a880491ede8e3c9be7":{
      "scriptId":"u52"},
    "2392bd5e0022497286cf9c02b3ca9615":{
      "scriptId":"u53"},
    "9da4dbfbe39641079b67a2268e60aa57":{
      "scriptId":"u54"},
    "af129290d218491ab88cc7a9046771e6":{
      "scriptId":"u55"},
    "78a09463ecdc489cabab1a8a12f9ca6a":{
      "scriptId":"u56"},
    "b49713889c5d4093a8ed73b8cb91bb35":{
      "scriptId":"u57"},
    "cf9cba57f30046628378a1aeedc6c0fc":{
      "scriptId":"u58"},
    "12ee1af996584f23a502575188f15d6c":{
      "scriptId":"u59"},
    "615861bced8b450dafdd2ba4520c0449":{
      "scriptId":"u60"},
    "6fe4736a3da74adc94d06dedcbb11c93":{
      "scriptId":"u61"},
    "420e6fb13ed448f1b0cfc55a745b0c26":{
      "scriptId":"u62"},
    "02267a22bf354b948e8299e479c886e6":{
      "scriptId":"u63"},
    "ffe3c835abe24f6ebe2106eb7bf078b3":{
      "scriptId":"u64"},
    "6d75c89ff8ae4964a9f3affc1bca5d0e":{
      "scriptId":"u65"},
    "457c0e52f4424bd59dbf1cd715b02a15":{
      "scriptId":"u66"},
    "857a9898c07641358ae21f6325e9534f":{
      "scriptId":"u67"},
    "70da91ad98bb4bd78f8bf13c0b95afc7":{
      "scriptId":"u68"},
    "b80f3c68ee644b59a5348bb3a44e59a5":{
      "scriptId":"u69"},
    "0baa23e384d242dcaa886756b2d93c5c":{
      "scriptId":"u70"},
    "d8a479ee0ef941be9892380fa484aa04":{
      "scriptId":"u71"},
    "f8d5a35eb00d4d79aadcda2c62e4ccb9":{
      "scriptId":"u72"},
    "e320ae7671974371ae0bba29f1a45908":{
      "scriptId":"u73"},
    "ecd9d093277b477bbf1930dc51b4b2c0":{
      "scriptId":"u74"},
    "8deeaa07c8d64e84a9047792eea2b13f":{
      "scriptId":"u75"},
    "726b821a16b44a00b38aa13767c1f2ea":{
      "scriptId":"u76"},
    "ba6085a4e5c549d488fdd755bd71e7b6":{
      "scriptId":"u77"},
    "a2dc01a99525414fb7d95d02ab262806":{
      "scriptId":"u78"},
    "022b108906b04c8381c307450005a0d6":{
      "scriptId":"u79"},
    "6e5699a88f8949aab8c1fcece535e4fa":{
      "scriptId":"u80"},
    "69889721c2a346d4ae12a8cc81accb68":{
      "scriptId":"u81"},
    "c9d7fc26db464de585fcc586accda72d":{
      "scriptId":"u82"},
    "4446c255058044deb9a5b2d2bd975e0e":{
      "scriptId":"u83"},
    "0dd7a5e0dc4d4164b588a9c3ab824d2c":{
      "scriptId":"u84"},
    "11ba7afe5c24402fb017f66f3a8739a5":{
      "scriptId":"u85"},
    "135b41af9d4049f0a03b0a41784822f7":{
      "scriptId":"u86"},
    "1b6e2c194d00412ea4fa8dc593f5b434":{
      "scriptId":"u87"},
    "587f488ffb634c45b3e61704fc1f417a":{
      "scriptId":"u88"},
    "d29370eea24c4f47b98e307b5e07726c":{
      "scriptId":"u89"},
    "7ed0e94ef2814019b2bec8968ed205f8":{
      "scriptId":"u90"},
    "d310e14a17484ac3b69014ef736261bf":{
      "scriptId":"u91"},
    "a166e2747a8e4ecaa889030e181f023f":{
      "scriptId":"u92"},
    "c56dcd08318e45f8bce5a19dc4693bc3":{
      "scriptId":"u93"},
    "2285a08d687549b6a90724987f41b63b":{
      "scriptId":"u94"},
    "533b7e62fc6e4160a85c6ad373fc3c29":{
      "scriptId":"u95"},
    "db31738fd19841cdbe7a4bc94e9e7f97":{
      "scriptId":"u96"},
    "3715070b6789464d87fd09bfc7d755fb":{
      "scriptId":"u97"},
    "b6c89ab485224f699b826d72dcf6f64d":{
      "scriptId":"u98"},
    "b6436f7c35094fc7af52694286324314":{
      "scriptId":"u99"},
    "3f82a705a62949aca919979b3775a150":{
      "scriptId":"u100"},
    "ada0f4dedc4047e7befea44a9bed5b30":{
      "scriptId":"u101"},
    "c90201eca11e4587be15e42ad23f2eae":{
      "scriptId":"u102"}}});