$axure.loadCurrentPage({
  "url":"mobilemaintenance.html",
  "generationDate":new Date(1503911354424.12),
  "isCanvasEnabled":false,
  "variables":["NavigationSpread"],
  "page":{
    "packageId":"91afe48656be4a67aa75bf7e2ad17bbc",
    "type":"Axure:Page",
    "name":"MobileMaintenance",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a2a44408f40b4a5dbeb9aad2d37589f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFCC66},
{
                  "color":0xFFFFCC66},
{
                  "color":0xFFECEF76},
{
                  "color":0xFFECEF76}]},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20a85a8a6ca24834a32592bcd32508ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFCC66},
{
                      "color":0xFFFFCC66},
{
                      "color":0xFFECEF76},
{
                      "color":0xFFECEF76}]},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u441.png"}},
{
          "id":"3fa76c9645c4464c9756fd772e6b6ae3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":480,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb7a66f67b00421d9bf7c62a4e2f0052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":480,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u443.png"}},
{
          "id":"7567c2655d1445869ad9a3a4ad244f12",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":50,
              "y":320},
            "size":{
              "width":380,
              "height":48}},
          "adaptiveStyles":{
},
          "placeholderText":"     用户名  "},
{
          "id":"63487048da104a738460616916c18cf6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":50,
              "y":390},
            "size":{
              "width":380,
              "height":48}},
          "adaptiveStyles":{
},
          "placeholderText":"      密码"},
{
          "id":"cd0ada2fc7d84c478e1e2b20b58afb74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1094BA}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF063C4A}},
              "disabled":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":50,
              "y":460},
            "size":{
              "width":380,
              "height":48},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dde3f27e2fe403eb44574d20911e95d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1094BA}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF063C4A}},
                  "disabled":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":50,
                  "y":460},
                "size":{
                  "width":380,
                  "height":48},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 Loading",
                      "objectsToFades":[{
                          "objectPath":["965f2ff97e3e44f4a33f7d60c4c49d0a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Main",
                      "target":{
                        "targetType":"page",
                        "url":"main.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/mobilemaintenance/u6.png",
            "mouseOver~":"images/mobilemaintenance/u6_mouseOver.png",
            "mouseDown~":"images/mobilemaintenance/u6_mouseDown.png",
            "disabled~":"images/mobilemaintenance/u6_disabled.png"}},
{
          "id":"965f2ff97e3e44f4a33f7d60c4c49d0a",
          "label":"Loading",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":140,
              "y":294},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0748fb2ed1b0464ea39ab80dff652825",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6e60bbd9815745179bb96ead797b7b3e",
                  "label":"",
                  "parentDynamicPanel":"965f2ff97e3e44f4a33f7d60c4c49d0a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0x99000000},
                    "size":{
                      "width":200,
                      "height":214},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"972cdc56ec6d4b44ba4860f386ec4e6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"965f2ff97e3e44f4a33f7d60c4c49d0a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0x99000000},
                        "size":{
                          "width":200,
                          "height":214},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/mobilemaintenance/u9.png"}},
{
                  "id":"004106ad930e40bebfbfd47e05fdbaa1",
                  "label":"",
                  "parentDynamicPanel":"965f2ff97e3e44f4a33f7d60c4c49d0a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":55,
                      "y":46},
                    "size":{
                      "width":90,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68d69185b1d04cebbcd2b773cefd0457",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"965f2ff97e3e44f4a33f7d60c4c49d0a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":55,
                          "y":46},
                        "size":{
                          "width":90,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/u34.gif"}},
{
                  "id":"f5035901bdf340cfb88f4696c19fff59",
                  "label":"",
                  "parentDynamicPanel":"965f2ff97e3e44f4a33f7d60c4c49d0a",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":55,
                      "y":154},
                    "size":{
                      "width":94,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4d140f79054d46008c465cc4f439c432",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"965f2ff97e3e44f4a33f7d60c4c49d0a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":55,
                          "y":154},
                        "size":{
                          "width":94,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"d30d75a796df45bdb4197ba339075a02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":33},
            "size":{
              "width":480,
              "height":261},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a116058e91e4e2c8846946bc050a8cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":480,
                  "height":261},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobilemaintenance/u15.png"}},
{
          "id":"3253829faf124944b7cda250b6516fb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'方正细黑一简体 Regular', '方正细黑一简体'",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":95.5,
              "y":118},
            "size":{
              "width":289,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54ccf2bd61ad4aee9fbd2d1769783c86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正细黑一简体 Regular', '方正细黑一简体'",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":95.5,
                  "y":118},
                "size":{
                  "width":289,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a2a44408f40b4a5dbeb9aad2d37589f4":{
      "scriptId":"u0"},
    "20a85a8a6ca24834a32592bcd32508ff":{
      "scriptId":"u1"},
    "3fa76c9645c4464c9756fd772e6b6ae3":{
      "scriptId":"u2"},
    "fb7a66f67b00421d9bf7c62a4e2f0052":{
      "scriptId":"u3"},
    "7567c2655d1445869ad9a3a4ad244f12":{
      "scriptId":"u4"},
    "63487048da104a738460616916c18cf6":{
      "scriptId":"u5"},
    "cd0ada2fc7d84c478e1e2b20b58afb74":{
      "scriptId":"u6"},
    "7dde3f27e2fe403eb44574d20911e95d":{
      "scriptId":"u7"},
    "965f2ff97e3e44f4a33f7d60c4c49d0a":{
      "scriptId":"u8"},
    "6e60bbd9815745179bb96ead797b7b3e":{
      "scriptId":"u9"},
    "972cdc56ec6d4b44ba4860f386ec4e6c":{
      "scriptId":"u10"},
    "004106ad930e40bebfbfd47e05fdbaa1":{
      "scriptId":"u11"},
    "68d69185b1d04cebbcd2b773cefd0457":{
      "scriptId":"u12"},
    "f5035901bdf340cfb88f4696c19fff59":{
      "scriptId":"u13"},
    "4d140f79054d46008c465cc4f439c432":{
      "scriptId":"u14"},
    "d30d75a796df45bdb4197ba339075a02":{
      "scriptId":"u15"},
    "6a116058e91e4e2c8846946bc050a8cd":{
      "scriptId":"u16"},
    "3253829faf124944b7cda250b6516fb6":{
      "scriptId":"u17"},
    "54ccf2bd61ad4aee9fbd2d1769783c86":{
      "scriptId":"u18"}}});