$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1503911327315.57),
  "isCanvasEnabled":false,
  "variables":["NavigationSpread"],
  "page":{
    "packageId":"cca0be32f2b64a6fa42dfab4ed887163",
    "type":"Axure:Page",
    "name":"Login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4f62343df9da450ba22768ab7030e88d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF24323F},
            "size":{
              "width":1260,
              "height":690}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cfb64fc851841dba1307333f36679e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF24323F},
                "size":{
                  "width":1260,
                  "height":690}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u0.png"}},
{
          "id":"1abe8717254c457ea0eeb07f8c67a32d",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":896,
              "height":690}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to 下一步 向左滑动 out 1000ms 向左滑动 in 1000ms wrap repeat every 3000 ms",
                      "panelsToStates":[{
                          "panelPath":["1abe8717254c457ea0eeb07f8c67a32d"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":3000,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":1000},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":1000},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"80669ef84f2244ec925c3e195ad4bb16",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a213def84eae4288b266b8d41d4f8934",
                  "label":"",
                  "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-33,
                      "y":0},
                    "size":{
                      "width":1075,
                      "height":690}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"612cfa01434a4d0fbf9bef2a978b162f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-33,
                          "y":0},
                        "size":{
                          "width":1075,
                          "height":690}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/u3.jpg"}},
{
                  "id":"380237aacfd74288a07b01ea4383bbda",
                  "label":"",
                  "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xBF000000},
                    "location":{
                      "x":150,
                      "y":552},
                    "size":{
                      "width":746,
                      "height":98},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd2b127467c8462bbc08b9e11e6249a7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xBF000000},
                        "location":{
                          "x":150,
                          "y":552},
                        "size":{
                          "width":746,
                          "height":98},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/u5.png"}}]},
{
              "id":"0eb85c28d7e0485dab4b57297247ec62",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1d97d2f2a36742558c86359cf90bf0fd",
                  "label":"",
                  "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-372,
                      "y":-10},
                    "size":{
                      "width":1692,
                      "height":697}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd3cccfd13ee452dbc5bdb15a3c1aaf5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-372,
                          "y":-10},
                        "size":{
                          "width":1692,
                          "height":697}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/u7.jpg"}},
{
                  "id":"48151f653274491384adf5c9b93e05b7",
                  "label":"",
                  "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xBF000000},
                    "location":{
                      "x":84,
                      "y":172},
                    "size":{
                      "width":746,
                      "height":98},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dfb4efbe7ac741adbee61ec744d71147",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xBF000000},
                        "location":{
                          "x":84,
                          "y":172},
                        "size":{
                          "width":746,
                          "height":98},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/u5.png"}}]},
{
              "id":"55fdc3ea92284fd18f193bb617021eac",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3e857427e0e2427cbca73ea3dc16271b",
                  "label":"",
                  "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-183,
                      "y":-162},
                    "size":{
                      "width":1243,
                      "height":897}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6fe3358124f848c493726871508d229e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-183,
                          "y":-162},
                        "size":{
                          "width":1243,
                          "height":897}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/u11.jpg"}},
{
                  "id":"fbbc790c06014ff5a6143dd8ad76c73b",
                  "label":"",
                  "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xBF000000},
                    "location":{
                      "x":0,
                      "y":340},
                    "size":{
                      "width":746,
                      "height":98},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1d94b311ab574f37904a4f0bf65d12a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1abe8717254c457ea0eeb07f8c67a32d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xBF000000},
                        "location":{
                          "x":0,
                          "y":340},
                        "size":{
                          "width":746,
                          "height":98},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/u5.png"}}]}]},
{
          "id":"5a5bbb1f086b40d9b1276fd732476f97",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006582},
            "location":{
              "x":924,
              "y":280},
            "size":{
              "width":306,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"681965cc28394ac6b1bfd3068ecc5604",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006582},
            "location":{
              "x":924,
              "y":350},
            "size":{
              "width":306,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"bee59ae30e3f44f5b91b4561c4175738",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":924,
              "y":258},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9df90330c4d34f4993607051722cc0b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":924,
                  "y":258},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da112574767e44ac88c51f8ab0569ac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":924,
              "y":328},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"208cf46bd89c47d8950a5a8ea3017489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":924,
                  "y":328},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf814ffaf46447c5adadb928cce85c73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1094BA}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF063C4A}},
              "disabled":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF09546A},
            "location":{
              "x":924,
              "y":440},
            "size":{
              "width":306,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f011770028444500abcb332de7275591",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1094BA}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF063C4A}},
                  "disabled":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF09546A},
                "location":{
                  "x":924,
                  "y":440},
                "size":{
                  "width":306,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 loading 向左滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["9d6b88413c0149b1bbb7ad4f64a4d38e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideLeft",
                              "duration":500,
                              "showType":"none"}}}]},
{
                      "action":"wait",
                      "description":"等待3000毫秒",
                      "waitTime":3000},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home3",
                      "target":{
                        "targetType":"page",
                        "url":"home3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u21.png",
            "mouseOver~":"images/login/u21_mouseOver.png",
            "mouseDown~":"images/login/u21_mouseDown.png",
            "disabled~":"images/login/u21_disabled.png"}},
{
          "id":"4ee16bf2f359491c994b09062f63753f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":924,
              "y":40},
            "size":{
              "width":306,
              "height":153},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF546172}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca120d2fa6ef418bae743ddb1adde189",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":924,
                  "y":40},
                "size":{
                  "width":306,
                  "height":153},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF546172}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u23.png"}},
{
          "id":"20362299cf7a450d8dde4222bffaf8b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF97EAFF,
              "opacity":1},
            "location":{
              "x":924,
              "y":638},
            "size":{
              "width":297,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e448b0c8c25d49078a99f8fefa0d9bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF97EAFF,
                  "opacity":1},
                "location":{
                  "x":924,
                  "y":638},
                "size":{
                  "width":297,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e716347586d94b9f994fb84b324d0a71",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1060,
              "y":390},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb2006da4bf34aee8b7c5f66a8cbdc8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1060,
                  "y":390},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9b8cdcec5f6e4f4d86037a34cd9ad5bd",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1156,
              "y":390},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30a07d534bfc45ebb5f308b052beee02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1156,
                  "y":390},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9d6b88413c0149b1bbb7ad4f64a4d38e",
          "label":"loading",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":896,
              "y":0},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"63b5fa29bd7f4cf0903d4b2e2e950bbc",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"29ec36423e824e58a0144e191bbb0e27",
                  "label":"",
                  "parentDynamicPanel":"9d6b88413c0149b1bbb7ad4f64a4d38e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF24323F},
                    "size":{
                      "width":364,
                      "height":690}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"65489baa4f264528a92c44257afd9d3e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d6b88413c0149b1bbb7ad4f64a4d38e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF24323F},
                        "size":{
                          "width":364,
                          "height":690}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/u32.png"}},
{
                  "id":"5d58e060bc92408fa39c9c4e1351e46a",
                  "label":"",
                  "parentDynamicPanel":"9d6b88413c0149b1bbb7ad4f64a4d38e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140.5,
                      "y":219},
                    "size":{
                      "width":81,
                      "height":81}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2a0be252c034850a8ac2b27ffe9ac8c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d6b88413c0149b1bbb7ad4f64a4d38e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140.5,
                          "y":219},
                        "size":{
                          "width":81,
                          "height":81}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/u34.gif"}},
{
                  "id":"223ffc90ed174e0f9b3df96f17e226e4",
                  "label":"",
                  "parentDynamicPanel":"9d6b88413c0149b1bbb7ad4f64a4d38e",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":134,
                      "y":378},
                    "size":{
                      "width":94,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2304595c8be64e4fadafce3bd80a8e0c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d6b88413c0149b1bbb7ad4f64a4d38e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":134,
                          "y":378},
                        "size":{
                          "width":94,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "4f62343df9da450ba22768ab7030e88d":{
      "scriptId":"u0"},
    "4cfb64fc851841dba1307333f36679e2":{
      "scriptId":"u1"},
    "1abe8717254c457ea0eeb07f8c67a32d":{
      "scriptId":"u2"},
    "a213def84eae4288b266b8d41d4f8934":{
      "scriptId":"u3"},
    "612cfa01434a4d0fbf9bef2a978b162f":{
      "scriptId":"u4"},
    "380237aacfd74288a07b01ea4383bbda":{
      "scriptId":"u5"},
    "cd2b127467c8462bbc08b9e11e6249a7":{
      "scriptId":"u6"},
    "1d97d2f2a36742558c86359cf90bf0fd":{
      "scriptId":"u7"},
    "cd3cccfd13ee452dbc5bdb15a3c1aaf5":{
      "scriptId":"u8"},
    "48151f653274491384adf5c9b93e05b7":{
      "scriptId":"u9"},
    "dfb4efbe7ac741adbee61ec744d71147":{
      "scriptId":"u10"},
    "3e857427e0e2427cbca73ea3dc16271b":{
      "scriptId":"u11"},
    "6fe3358124f848c493726871508d229e":{
      "scriptId":"u12"},
    "fbbc790c06014ff5a6143dd8ad76c73b":{
      "scriptId":"u13"},
    "1d94b311ab574f37904a4f0bf65d12a0":{
      "scriptId":"u14"},
    "5a5bbb1f086b40d9b1276fd732476f97":{
      "scriptId":"u15"},
    "681965cc28394ac6b1bfd3068ecc5604":{
      "scriptId":"u16"},
    "bee59ae30e3f44f5b91b4561c4175738":{
      "scriptId":"u17"},
    "9df90330c4d34f4993607051722cc0b2":{
      "scriptId":"u18"},
    "da112574767e44ac88c51f8ab0569ac8":{
      "scriptId":"u19"},
    "208cf46bd89c47d8950a5a8ea3017489":{
      "scriptId":"u20"},
    "bf814ffaf46447c5adadb928cce85c73":{
      "scriptId":"u21"},
    "f011770028444500abcb332de7275591":{
      "scriptId":"u22"},
    "4ee16bf2f359491c994b09062f63753f":{
      "scriptId":"u23"},
    "ca120d2fa6ef418bae743ddb1adde189":{
      "scriptId":"u24"},
    "20362299cf7a450d8dde4222bffaf8b5":{
      "scriptId":"u25"},
    "e448b0c8c25d49078a99f8fefa0d9bdf":{
      "scriptId":"u26"},
    "e716347586d94b9f994fb84b324d0a71":{
      "scriptId":"u27"},
    "eb2006da4bf34aee8b7c5f66a8cbdc8a":{
      "scriptId":"u28"},
    "9b8cdcec5f6e4f4d86037a34cd9ad5bd":{
      "scriptId":"u29"},
    "30a07d534bfc45ebb5f308b052beee02":{
      "scriptId":"u30"},
    "9d6b88413c0149b1bbb7ad4f64a4d38e":{
      "scriptId":"u31"},
    "29ec36423e824e58a0144e191bbb0e27":{
      "scriptId":"u32"},
    "65489baa4f264528a92c44257afd9d3e":{
      "scriptId":"u33"},
    "5d58e060bc92408fa39c9c4e1351e46a":{
      "scriptId":"u34"},
    "f2a0be252c034850a8ac2b27ffe9ac8c":{
      "scriptId":"u35"},
    "223ffc90ed174e0f9b3df96f17e226e4":{
      "scriptId":"u36"},
    "2304595c8be64e4fadafce3bd80a8e0c":{
      "scriptId":"u37"}}});