$axure.loadCurrentPage({
  "url":"knowledgestorage_1.html",
  "generationDate":new Date(1503911358322.35),
  "isCanvasEnabled":false,
  "variables":["NavigationSpread"],
  "page":{
    "packageId":"ac003b6676ae4def98ea01c5d7181089",
    "type":"Axure:Page",
    "name":"KnowledgeStorage",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4909724b43c34ceb9b06e873fc3d2068",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFCC66},
{
                  "color":0xFFFFCC66},
{
                  "color":0xFFECEF76},
{
                  "color":0xFFECEF76}]},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cac609f5206149cf94ea2e445f0b33dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFCC66},
{
                      "color":0xFFFFCC66},
{
                      "color":0xFFECEF76},
{
                      "color":0xFFECEF76}]},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u441.png"}},
{
          "id":"d9205ffe726640f2bc82cb94a477fdcf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":480,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9348d47f1344ead9b0b8f805e2c29a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":480,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u443.png"}},
{
          "id":"142caf8ebb2e4bd7ac623c46f6d49b9c",
          "label":"content",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":480,
              "height":750}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"67388cd6c7af43fea49a9c94585ef068",
              "label":"MENUE",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7a38f4d0d87a43c1bef0b0b62f33cbca",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x4C000000}},
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7F000000}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0x33000000},
                    "location":{
                      "x":19,
                      "y":0},
                    "size":{
                      "width":92,
                      "height":48},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd56147c617e4bf38a62186162bf93dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0x4C000000}},
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0x7F000000}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0x33000000},
                        "location":{
                          "x":19,
                          "y":0},
                        "size":{
                          "width":92,
                          "height":48},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 Main",
                              "target":{
                                "targetType":"page",
                                "url":"main.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/main/u900.png",
                    "mouseOver~":"images/main/u900_mouseOver.png",
                    "mouseDown~":"images/main/u900_mouseDown.png"}},
{
                  "id":"24decb5f9593439593a754be665d53a8",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":29,
                      "y":8},
                    "size":{
                      "width":32,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb765857475e4cb9a3c09bf4a878b150",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":29,
                          "y":8},
                        "size":{
                          "width":32,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home3/u1031.png"}},
{
                  "id":"7a1619ea35f64f83bf1e5b308629d414",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"400",
                    "location":{
                      "x":193,
                      "y":10},
                    "size":{
                      "width":73,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0666088f4863411da3291c46cbc5a5a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontWeight":"400",
                        "location":{
                          "x":193,
                          "y":10},
                        "size":{
                          "width":73,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"76b8516aac254fb394fcebf0b79f33cb",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}}},
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":480,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b8f68fb6d7da43e6a3795f8497ba2510",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2}}},
                        "location":{
                          "x":0,
                          "y":80},
                        "size":{
                          "width":480,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 content to DOC 向左滑动 out 500ms 向左滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["142caf8ebb2e4bd7ac623c46f6d49b9c"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/resource/u435.png",
                    "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
                  "id":"e1fdeb2be4814dc1a43f1b23648acc6a",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}}},
                    "location":{
                      "x":0,
                      "y":127},
                    "size":{
                      "width":480,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2f88c3616204f3d8c4e597963286e92",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2}}},
                        "location":{
                          "x":0,
                          "y":127},
                        "size":{
                          "width":480,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 content to DOC 向左滑动 out 500ms 向左滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["142caf8ebb2e4bd7ac623c46f6d49b9c"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/resource/u435.png",
                    "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
                  "id":"b66ffe82c1554a20a89693b75ecfabff",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}}},
                    "location":{
                      "x":0,
                      "y":174},
                    "size":{
                      "width":480,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d732faa33ba549238ba62a89357bcd17",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2}}},
                        "location":{
                          "x":0,
                          "y":174},
                        "size":{
                          "width":480,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 content to DOC 向左滑动 out 500ms 向左滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["142caf8ebb2e4bd7ac623c46f6d49b9c"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/resource/u435.png",
                    "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
                  "id":"d6d6dde195754cf7b561131626816e66",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}}},
                    "location":{
                      "x":0,
                      "y":221},
                    "size":{
                      "width":480,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3ffb2a4403e4dfdb57be6e55801c648",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2}}},
                        "location":{
                          "x":0,
                          "y":221},
                        "size":{
                          "width":480,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 content to DOC 向左滑动 out 500ms 向左滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["142caf8ebb2e4bd7ac623c46f6d49b9c"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/resource/u435.png",
                    "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
                  "id":"6b9108d7145b49d093e2eb4827b6fb33",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "location":{
                      "x":440,
                      "y":92},
                    "size":{
                      "width":24,
                      "height":24},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56bd8e70bf6c47a39dfcc21def434d1a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "location":{
                          "x":440,
                          "y":92},
                        "size":{
                          "width":24,
                          "height":24},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/main/u60.png"}},
{
                  "id":"49ea7481678d41feb0da80cc03c44a27",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "location":{
                      "x":440,
                      "y":140},
                    "size":{
                      "width":24,
                      "height":24},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c2bc77e5e524490caf063d0281dbb335",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "location":{
                          "x":440,
                          "y":140},
                        "size":{
                          "width":24,
                          "height":24},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/main/u60.png"}},
{
                  "id":"a9956665b89245daac736a9d7abd79e9",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "location":{
                      "x":440,
                      "y":186},
                    "size":{
                      "width":24,
                      "height":24},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13ec0bae11f94df18ebc8cbaaefdd675",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "location":{
                          "x":440,
                          "y":186},
                        "size":{
                          "width":24,
                          "height":24},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/main/u60.png"}},
{
                  "id":"5a3a04f8322c40ae86b31aa7192f7ff9",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "location":{
                      "x":440,
                      "y":232},
                    "size":{
                      "width":24,
                      "height":24},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76cf7cbfbf2b496191c1ff463e26d1bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "location":{
                          "x":440,
                          "y":232},
                        "size":{
                          "width":24,
                          "height":24},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/main/u60.png"}},
{
                  "id":"6eb17b58699e4d6290d28f14cd81724f",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}}},
                    "location":{
                      "x":0,
                      "y":268},
                    "size":{
                      "width":480,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74cc0d097bed4965a54339fda34c79b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2}}},
                        "location":{
                          "x":0,
                          "y":268},
                        "size":{
                          "width":480,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 content to DOC 向左滑动 out 500ms 向左滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["142caf8ebb2e4bd7ac623c46f6d49b9c"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/resource/u435.png",
                    "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
                  "id":"1f87581df3fb409babfc81e125681b3a",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "location":{
                      "x":440,
                      "y":280},
                    "size":{
                      "width":24,
                      "height":24},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c34522e8ab044f509cd2f7064bc082b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "location":{
                          "x":440,
                          "y":280},
                        "size":{
                          "width":24,
                          "height":24},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/main/u60.png"}},
{
                  "id":"67130e1bada7493ebf743368149891b5",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":88.5},
                    "size":{
                      "width":31,
                      "height":31},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33e762df87e54cd28100d33e312580ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":88.5},
                        "size":{
                          "width":31,
                          "height":31},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/main/u202.png"}},
{
                  "id":"c3ef96e74d7145b599ee8b46b0b0475d",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":136.5},
                    "size":{
                      "width":31,
                      "height":31},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be9c60e8a8d04cc3b289b51f9f64089b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":136.5},
                        "size":{
                          "width":31,
                          "height":31},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/main/u927.png"}},
{
                  "id":"6e30e02116094f2bb3457ed1c25c9e73",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":186},
                    "size":{
                      "width":31,
                      "height":31},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99ac40f073b146c898be96f92b577780",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":186},
                        "size":{
                          "width":31,
                          "height":31},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/main/u929.png"}},
{
                  "id":"fffd6e7860ee45688eab96072a1d4c3f",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":227},
                    "size":{
                      "width":31,
                      "height":31},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"270d01da684840ff9c7ed12ff081be51",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":227},
                        "size":{
                          "width":31,
                          "height":31},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/knowledgestorage_1/u37.png"}},
{
                  "id":"85332cf7a9314aa79a039d4f292cd673",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":276.5},
                    "size":{
                      "width":31,
                      "height":31},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a2b6f1058c0a4be38cdb42a1f8550362",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":276.5},
                        "size":{
                          "width":31,
                          "height":31},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/knowledgestorage_1/u39.png"}}]},
{
              "id":"dffc25be19d849b8896dfb2c5baddc6c",
              "label":"DOC",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"701ea69b5a3042ef8b245de2722f84b5",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x4C000000}},
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7F000000}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0x33000000},
                    "location":{
                      "x":19,
                      "y":0},
                    "size":{
                      "width":92,
                      "height":48},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1093bcf5db38486a938697f97624f183",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0x4C000000}},
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0x7F000000}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0x33000000},
                        "location":{
                          "x":19,
                          "y":0},
                        "size":{
                          "width":92,
                          "height":48},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 content to MENUE 向右滑动 out 500ms 向右滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["142caf8ebb2e4bd7ac623c46f6d49b9c"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideRight",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideRight",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/main/u900.png",
                    "mouseOver~":"images/main/u900_mouseOver.png",
                    "mouseDown~":"images/main/u900_mouseDown.png"}},
{
                  "id":"6a70a305ef8d4aacb192affa9c803ef3",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":29,
                      "y":8},
                    "size":{
                      "width":32,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ac22d3829bb46d9a4a7ee334b156e75",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":29,
                          "y":8},
                        "size":{
                          "width":32,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home3/u1031.png"}},
{
                  "id":"05580e22700b4d5d8999f4a5e92f7bdc",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"400",
                    "location":{
                      "x":193,
                      "y":10},
                    "size":{
                      "width":97,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0b7212d81c0e43fc84c1f693dde0755f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontWeight":"400",
                        "location":{
                          "x":193,
                          "y":10},
                        "size":{
                          "width":97,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"49a48881091b4f6db4d8778e80186c36",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}}},
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":480,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d4e7cff039404b9db6b9d437c62b86fc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"left",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2}}},
                        "location":{
                          "x":0,
                          "y":80},
                        "size":{
                          "width":480,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 SucceedFeedBack/Succeed to Content",
                              "panelsToStates":[{
                                  "panelPath":["bc31f1e0b3eb44a1b861a73e82c6e361",
"fcedc6112d0342aeb42df88b7a639055"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/resource/u435.png",
                    "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
                  "id":"42dc90c7d7494596bb3e0a665af394e6",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}}},
                    "location":{
                      "x":0,
                      "y":127},
                    "size":{
                      "width":480,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f595a170bad84e5e9f38ca7faca31918",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"left",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2}}},
                        "location":{
                          "x":0,
                          "y":127},
                        "size":{
                          "width":480,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF666666}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 SucceedFeedBack/Succeed to Content",
                              "panelsToStates":[{
                                  "panelPath":["bc31f1e0b3eb44a1b861a73e82c6e361",
"fcedc6112d0342aeb42df88b7a639055"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/resource/u435.png",
                    "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
                  "id":"4d50e4c238004b38a83ae22158bae7db",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":440,
                      "y":93},
                    "size":{
                      "width":24,
                      "height":24},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f22f396a4114ab28f6daa88dd4a7506",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":440,
                          "y":93},
                        "size":{
                          "width":24,
                          "height":24},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/knowledgestorage_1/u51.png"}},
{
                  "id":"21e443cefdc04b05907983cda409668e",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":440,
                      "y":140},
                    "size":{
                      "width":24,
                      "height":24},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68774d949bad49048536795b7c3f43d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":440,
                          "y":140},
                        "size":{
                          "width":24,
                          "height":24},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/knowledgestorage_1/u51.png"}},
{
                  "id":"6e1d4fcb969a4e0db312e7f3038711ba",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":85.5},
                    "size":{
                      "width":37,
                      "height":37},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0175e1601018400da1cb326cdf9baabf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":85.5},
                        "size":{
                          "width":37,
                          "height":37},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/main/u952.png"}},
{
                  "id":"497b19038e89425b84ada9010a4dd2bb",
                  "label":"",
                  "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":133},
                    "size":{
                      "width":37,
                      "height":37},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19ae258f0c3446349402804608abbdb8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"142caf8ebb2e4bd7ac623c46f6d49b9c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":133},
                        "size":{
                          "width":37,
                          "height":37},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/main/u952.png"}}]}]},
{
          "id":"bc31f1e0b3eb44a1b861a73e82c6e361",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":290}},
          "adaptiveStyles":{
},
          "masterId":"e6940efacd3d4d8cb5e88e4af318f50c"}]}},
  "masters":{
    "e6940efacd3d4d8cb5e88e4af318f50c":{
      "packageId":"e6940efacd3d4d8cb5e88e4af318f50c",
      "type":"Axure:Master",
      "name":"SucceedFeedBack",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fcedc6112d0342aeb42df88b7a639055",
            "label":"Succeed",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onPanelStateChange":{
                "description":"OnPanelStateChange",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"显示 (形状) 淡入淡出 500 ms",
                        "objectsToFades":[{
                            "objectPath":["9c39ae157943439283df90fb21dc290d"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "easing":"fade",
                                "duration":500,
                                "showType":"none"}}}]},
{
                        "action":"wait",
                        "description":"等待2000毫秒",
                        "waitTime":2000},
{
                        "action":"fadeWidget",
                        "description":"隐藏 (形状) 淡入淡出 500 ms",
                        "objectsToFades":[{
                            "objectPath":["9c39ae157943439283df90fb21dc290d"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "easing":"fade",
                                "duration":500,
                                "showType":"none"}}}]},
{
                        "action":"setPanelState",
                        "description":"设置 Succeed to none",
                        "panelsToStates":[{
                            "panelPath":["fcedc6112d0342aeb42df88b7a639055"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":1,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"d58ddc77dd0c4e53baa37a678e437f93",
                "label":"none",
                "type":"Axure:PanelDiagram",
                "objects":[]},
{
                "id":"6e4803cdc7374c9ca3e7d943c19e8674",
                "label":"Content",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"9c39ae157943439283df90fb21dc290d",
                    "label":"",
                    "parentDynamicPanel":"fcedc6112d0342aeb42df88b7a639055",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":false,
                    "style":{
                      "fontSize":"20px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
},
                        "mouseDown":{
}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0085B0},
                      "size":{
                        "width":220,
                        "height":100},
                      "visible":false,
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"4"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0909e5187b5343409a65068aeb640b21",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fcedc6112d0342aeb42df88b7a639055",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":false,
                        "style":{
                          "fontSize":"20px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
},
                            "mouseDown":{
}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF0085B0},
                          "size":{
                            "width":220,
                            "height":100},
                          "visible":false,
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"4"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/devicemanagement/u1834.png"}}]}]}]}}},
  "objectPaths":{
    "4909724b43c34ceb9b06e873fc3d2068":{
      "scriptId":"u0"},
    "cac609f5206149cf94ea2e445f0b33dd":{
      "scriptId":"u1"},
    "d9205ffe726640f2bc82cb94a477fdcf":{
      "scriptId":"u2"},
    "b9348d47f1344ead9b0b8f805e2c29a4":{
      "scriptId":"u3"},
    "142caf8ebb2e4bd7ac623c46f6d49b9c":{
      "scriptId":"u4"},
    "7a38f4d0d87a43c1bef0b0b62f33cbca":{
      "scriptId":"u5"},
    "cd56147c617e4bf38a62186162bf93dd":{
      "scriptId":"u6"},
    "24decb5f9593439593a754be665d53a8":{
      "scriptId":"u7"},
    "cb765857475e4cb9a3c09bf4a878b150":{
      "scriptId":"u8"},
    "7a1619ea35f64f83bf1e5b308629d414":{
      "scriptId":"u9"},
    "0666088f4863411da3291c46cbc5a5a0":{
      "scriptId":"u10"},
    "76b8516aac254fb394fcebf0b79f33cb":{
      "scriptId":"u11"},
    "b8f68fb6d7da43e6a3795f8497ba2510":{
      "scriptId":"u12"},
    "e1fdeb2be4814dc1a43f1b23648acc6a":{
      "scriptId":"u13"},
    "f2f88c3616204f3d8c4e597963286e92":{
      "scriptId":"u14"},
    "b66ffe82c1554a20a89693b75ecfabff":{
      "scriptId":"u15"},
    "d732faa33ba549238ba62a89357bcd17":{
      "scriptId":"u16"},
    "d6d6dde195754cf7b561131626816e66":{
      "scriptId":"u17"},
    "c3ffb2a4403e4dfdb57be6e55801c648":{
      "scriptId":"u18"},
    "6b9108d7145b49d093e2eb4827b6fb33":{
      "scriptId":"u19"},
    "56bd8e70bf6c47a39dfcc21def434d1a":{
      "scriptId":"u20"},
    "49ea7481678d41feb0da80cc03c44a27":{
      "scriptId":"u21"},
    "c2bc77e5e524490caf063d0281dbb335":{
      "scriptId":"u22"},
    "a9956665b89245daac736a9d7abd79e9":{
      "scriptId":"u23"},
    "13ec0bae11f94df18ebc8cbaaefdd675":{
      "scriptId":"u24"},
    "5a3a04f8322c40ae86b31aa7192f7ff9":{
      "scriptId":"u25"},
    "76cf7cbfbf2b496191c1ff463e26d1bc":{
      "scriptId":"u26"},
    "6eb17b58699e4d6290d28f14cd81724f":{
      "scriptId":"u27"},
    "74cc0d097bed4965a54339fda34c79b5":{
      "scriptId":"u28"},
    "1f87581df3fb409babfc81e125681b3a":{
      "scriptId":"u29"},
    "c34522e8ab044f509cd2f7064bc082b0":{
      "scriptId":"u30"},
    "67130e1bada7493ebf743368149891b5":{
      "scriptId":"u31"},
    "33e762df87e54cd28100d33e312580ec":{
      "scriptId":"u32"},
    "c3ef96e74d7145b599ee8b46b0b0475d":{
      "scriptId":"u33"},
    "be9c60e8a8d04cc3b289b51f9f64089b":{
      "scriptId":"u34"},
    "6e30e02116094f2bb3457ed1c25c9e73":{
      "scriptId":"u35"},
    "99ac40f073b146c898be96f92b577780":{
      "scriptId":"u36"},
    "fffd6e7860ee45688eab96072a1d4c3f":{
      "scriptId":"u37"},
    "270d01da684840ff9c7ed12ff081be51":{
      "scriptId":"u38"},
    "85332cf7a9314aa79a039d4f292cd673":{
      "scriptId":"u39"},
    "a2b6f1058c0a4be38cdb42a1f8550362":{
      "scriptId":"u40"},
    "701ea69b5a3042ef8b245de2722f84b5":{
      "scriptId":"u41"},
    "1093bcf5db38486a938697f97624f183":{
      "scriptId":"u42"},
    "6a70a305ef8d4aacb192affa9c803ef3":{
      "scriptId":"u43"},
    "2ac22d3829bb46d9a4a7ee334b156e75":{
      "scriptId":"u44"},
    "05580e22700b4d5d8999f4a5e92f7bdc":{
      "scriptId":"u45"},
    "0b7212d81c0e43fc84c1f693dde0755f":{
      "scriptId":"u46"},
    "49a48881091b4f6db4d8778e80186c36":{
      "scriptId":"u47"},
    "d4e7cff039404b9db6b9d437c62b86fc":{
      "scriptId":"u48"},
    "42dc90c7d7494596bb3e0a665af394e6":{
      "scriptId":"u49"},
    "f595a170bad84e5e9f38ca7faca31918":{
      "scriptId":"u50"},
    "4d50e4c238004b38a83ae22158bae7db":{
      "scriptId":"u51"},
    "2f22f396a4114ab28f6daa88dd4a7506":{
      "scriptId":"u52"},
    "21e443cefdc04b05907983cda409668e":{
      "scriptId":"u53"},
    "68774d949bad49048536795b7c3f43d9":{
      "scriptId":"u54"},
    "6e1d4fcb969a4e0db312e7f3038711ba":{
      "scriptId":"u55"},
    "0175e1601018400da1cb326cdf9baabf":{
      "scriptId":"u56"},
    "497b19038e89425b84ada9010a4dd2bb":{
      "scriptId":"u57"},
    "19ae258f0c3446349402804608abbdb8":{
      "scriptId":"u58"},
    "bc31f1e0b3eb44a1b861a73e82c6e361":{
      "scriptId":"u59",
      "fcedc6112d0342aeb42df88b7a639055":{
        "scriptId":"u60"},
      "9c39ae157943439283df90fb21dc290d":{
        "scriptId":"u61"},
      "0909e5187b5343409a65068aeb640b21":{
        "scriptId":"u62"}}}});