$axure.loadCurrentPage({
  "url":"inform.html",
  "generationDate":new Date(1503911356553.25),
  "isCanvasEnabled":false,
  "variables":["NavigationSpread"],
  "page":{
    "packageId":"5acd5f842bdd42f497198b792a61de16",
    "type":"Axure:Page",
    "name":"Inform",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ff8b1a67bf4842b7a140f151527cc37c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFCC66},
{
                  "color":0xFFFFCC66},
{
                  "color":0xFFECEF76},
{
                  "color":0xFFECEF76}]},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12d4bcb5ff0549daa6a32fec23b93b63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFCC66},
{
                      "color":0xFFFFCC66},
{
                      "color":0xFFECEF76},
{
                      "color":0xFFECEF76}]},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u441.png"}},
{
          "id":"321a898b26544fa0bdf145a5f0932336",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":480,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"963dbd20111a4e379cc757ff0b9e6502",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":480,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/resource/u443.png"}},
{
          "id":"5513453924fb4920afdb5bc338a712e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":208,
              "y":48},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0956b8adb075415691fbee5c11215ec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":208,
                  "y":48},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3638da6550e648dab89472de7409e94c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":112},
            "size":{
              "width":478,
              "height":687},
            "borderWidth":"-1",
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a2579fdbc084b45936e59f453a04b3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":112},
                "size":{
                  "width":478,
                  "height":687},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/inform/u6.png"}},
{
          "id":"9429fe1e967a4ba7aa362ef225c971c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":112},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef55bc9f7cfe45f5a39a3456183dbf83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":112},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Events",
                      "target":{
                        "targetType":"page",
                        "url":"events_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"272580a1497841689a9886fb332cd6e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":158},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9512a922c5b64f96a39371150a89823d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":158},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"242240cf51da4fb6b4380aa3cd7ecec4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":204},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53c528ece8be430b8f99479ab4dbfabe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":204},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"077879ceeb9e4312a44a6a0230b24f54",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":251},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"815c9e9df4c7467f977e86a323b1fc76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":251},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"d36a307c1fb2461b89ece4b38dfc0dc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":297},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f2dd8c05106437987a5db386a98dfb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":297},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"af5bc2c1e2d9402a8e15d6a53eb4dc9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":343},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0c52082865248889e0242bc0ce78398",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":343},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"f0fbe69c791345b1aa5c4a052ed7fec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":390},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9f9fc20a7bc464e8013560b89a037a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":390},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"144aa87b640c4f66a12ad395d45bd3d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":436},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387325ed8fa24f369ca645ec7f198454",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":436},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"e44535b11c024db7949659ed720146a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":482},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eaf9dcd70ed4938beea5ec429367010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":482},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"5055d1b0d6614128aa5b7af1fc0b5c65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":529},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59da591741b848ac9fd4b6b83f38c25a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":529},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"352c551653c34cf38281e87f64e470ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":575},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b823fcb3edb24c9eb1fb379ffa08b9e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":575},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"099f27d43f6146c3a28b3dca5ac51f1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":0,
              "y":621},
            "size":{
              "width":480,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40b626100e344760a0cb79078fa1f596",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":0,
                  "y":621},
                "size":{
                  "width":480,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Orders",
                      "target":{
                        "targetType":"page",
                        "url":"orders_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/resource/u435.png",
            "mouseOver~":"images/resource/u435_mouseOver.png"}},
{
          "id":"4cc61447f1ea45438d8aa0a405d6a41d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":128},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29e13fabddb040deac6eb2f31366f27a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":128},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af0afe0fbcd64980b36525fcf7dc0925",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":174},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8063c8e3770d4a6c84c51bd6749b2196",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":174},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5e76ab1048d4bbfb1abf2a6212173f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":220},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4feaf186f284dd5b376a34e002a6b59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":220},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0c0fd77f48e40e3968786bb4591df0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":267},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44b3008e782b4d819ed040a686e5dee7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":267},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0ac1921d04642a6acf56d564932af38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":313},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13771edb89d449809c3ebe5996b9d99c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":313},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6e681d8f4d24bb3af46fe510ed18429",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":360},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"370bb6095e9141c9bb393c6d9e0c29d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":360},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d37a925ea5504e73986897af57a3b476",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":406},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"095e3bfd290a4a31813e18a8d208478d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":406},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1034a8f47f8e4c11a9ff10052c0ea760",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":452},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4081908ad8804aaa9d20edda003529ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":452},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9a6f02d9f074ce5ab1cf9edbcdf09ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":498},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c943e8b106f74c1f97560c36de202377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":498},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bd6ca4be3ba4cfeaf2a30f882470df4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":544},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a490dc0dea914c5687b96ae3f6d6c192",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":544},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fa2cae6dce141e380641623f1469760",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":590},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8501e5c9bca646ae83590a3037dcf0d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":590},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"616d07a925aa4ad883cb948a0b34d3c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":358,
              "y":636},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"638b16e84b9e4829bae8078ffca81d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":636},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ff8b1a67bf4842b7a140f151527cc37c":{
      "scriptId":"u0"},
    "12d4bcb5ff0549daa6a32fec23b93b63":{
      "scriptId":"u1"},
    "321a898b26544fa0bdf145a5f0932336":{
      "scriptId":"u2"},
    "963dbd20111a4e379cc757ff0b9e6502":{
      "scriptId":"u3"},
    "5513453924fb4920afdb5bc338a712e8":{
      "scriptId":"u4"},
    "0956b8adb075415691fbee5c11215ec0":{
      "scriptId":"u5"},
    "3638da6550e648dab89472de7409e94c":{
      "scriptId":"u6"},
    "6a2579fdbc084b45936e59f453a04b3c":{
      "scriptId":"u7"},
    "9429fe1e967a4ba7aa362ef225c971c7":{
      "scriptId":"u8"},
    "ef55bc9f7cfe45f5a39a3456183dbf83":{
      "scriptId":"u9"},
    "272580a1497841689a9886fb332cd6e6":{
      "scriptId":"u10"},
    "9512a922c5b64f96a39371150a89823d":{
      "scriptId":"u11"},
    "242240cf51da4fb6b4380aa3cd7ecec4":{
      "scriptId":"u12"},
    "53c528ece8be430b8f99479ab4dbfabe":{
      "scriptId":"u13"},
    "077879ceeb9e4312a44a6a0230b24f54":{
      "scriptId":"u14"},
    "815c9e9df4c7467f977e86a323b1fc76":{
      "scriptId":"u15"},
    "d36a307c1fb2461b89ece4b38dfc0dc5":{
      "scriptId":"u16"},
    "3f2dd8c05106437987a5db386a98dfb6":{
      "scriptId":"u17"},
    "af5bc2c1e2d9402a8e15d6a53eb4dc9a":{
      "scriptId":"u18"},
    "a0c52082865248889e0242bc0ce78398":{
      "scriptId":"u19"},
    "f0fbe69c791345b1aa5c4a052ed7fec7":{
      "scriptId":"u20"},
    "e9f9fc20a7bc464e8013560b89a037a6":{
      "scriptId":"u21"},
    "144aa87b640c4f66a12ad395d45bd3d0":{
      "scriptId":"u22"},
    "387325ed8fa24f369ca645ec7f198454":{
      "scriptId":"u23"},
    "e44535b11c024db7949659ed720146a4":{
      "scriptId":"u24"},
    "9eaf9dcd70ed4938beea5ec429367010":{
      "scriptId":"u25"},
    "5055d1b0d6614128aa5b7af1fc0b5c65":{
      "scriptId":"u26"},
    "59da591741b848ac9fd4b6b83f38c25a":{
      "scriptId":"u27"},
    "352c551653c34cf38281e87f64e470ff":{
      "scriptId":"u28"},
    "b823fcb3edb24c9eb1fb379ffa08b9e9":{
      "scriptId":"u29"},
    "099f27d43f6146c3a28b3dca5ac51f1b":{
      "scriptId":"u30"},
    "40b626100e344760a0cb79078fa1f596":{
      "scriptId":"u31"},
    "4cc61447f1ea45438d8aa0a405d6a41d":{
      "scriptId":"u32"},
    "29e13fabddb040deac6eb2f31366f27a":{
      "scriptId":"u33"},
    "af0afe0fbcd64980b36525fcf7dc0925":{
      "scriptId":"u34"},
    "8063c8e3770d4a6c84c51bd6749b2196":{
      "scriptId":"u35"},
    "c5e76ab1048d4bbfb1abf2a6212173f8":{
      "scriptId":"u36"},
    "c4feaf186f284dd5b376a34e002a6b59":{
      "scriptId":"u37"},
    "b0c0fd77f48e40e3968786bb4591df0c":{
      "scriptId":"u38"},
    "44b3008e782b4d819ed040a686e5dee7":{
      "scriptId":"u39"},
    "e0ac1921d04642a6acf56d564932af38":{
      "scriptId":"u40"},
    "13771edb89d449809c3ebe5996b9d99c":{
      "scriptId":"u41"},
    "f6e681d8f4d24bb3af46fe510ed18429":{
      "scriptId":"u42"},
    "370bb6095e9141c9bb393c6d9e0c29d7":{
      "scriptId":"u43"},
    "d37a925ea5504e73986897af57a3b476":{
      "scriptId":"u44"},
    "095e3bfd290a4a31813e18a8d208478d":{
      "scriptId":"u45"},
    "1034a8f47f8e4c11a9ff10052c0ea760":{
      "scriptId":"u46"},
    "4081908ad8804aaa9d20edda003529ca":{
      "scriptId":"u47"},
    "c9a6f02d9f074ce5ab1cf9edbcdf09ef":{
      "scriptId":"u48"},
    "c943e8b106f74c1f97560c36de202377":{
      "scriptId":"u49"},
    "4bd6ca4be3ba4cfeaf2a30f882470df4":{
      "scriptId":"u50"},
    "a490dc0dea914c5687b96ae3f6d6c192":{
      "scriptId":"u51"},
    "6fa2cae6dce141e380641623f1469760":{
      "scriptId":"u52"},
    "8501e5c9bca646ae83590a3037dcf0d8":{
      "scriptId":"u53"},
    "616d07a925aa4ad883cb948a0b34d3c2":{
      "scriptId":"u54"},
    "638b16e84b9e4829bae8078ffca81d97":{
      "scriptId":"u55"}}});